### ISSUE TITLE
用户态和内核态切换的主要开销在哪里

### ISSUE THREAD

**Issue by liusy58** [Tyler-ytr/Interview_experience#2]
主要开销可能主要还是在与缓存的问题，从内核态切换到用户态之后，为了**安全**的问题，现在的操作系统要求必须要刷新缓存，所以想了很多的办法来减少系统调用的开销。

**Comment by Tyler-ytr** [comment]
感谢！

**Comment by Tyler-ytr** [comment]
感谢！目前答案文件中该问题回答为：保存寄存器（直接开销小）、检查权限、打乱执行流（间接开销小）、切换到内核栈（缓存冷，间接开销大），如果是系统调用还需要来回拷贝参数（直接开销大）
